In [ ]:
#Задание 1

In [21]:
import numpy as np

N = int(input('Введите количество элементов: '))
np.arange(N)[::-1]

Введите количество элементов: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
#Задание 2

In [24]:
import numpy as np

N = int(input('Введите количество элементов: '))
matrix = np.diag(np.arange(N, 0, -1))
print('сумма: {}'.format(sum(sum(matrix))))

Введите количество элементов: 5
сумма: 15


In [25]:
#проверка
np.diag(np.arange(N, 0, -1))

array([[5, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
#Задание 3

In [26]:
import numpy as np

a = np.array([[4,2,1], [1,3,0], [0,5,4]])
b = np.array([4,12,-3])
from numpy import linalg
linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [ ]:
#Задание 4

In [33]:
import numpy as np

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cosine(users_stats, next_user_stats):
    users_stats_Length = np.linalg.norm(users_stats)
    next_user_stats_Length = np.linalg.norm(next_user_stats)
    
    return np.dot(users_stats, next_user_stats) / ( users_stats_Length * next_user_stats_Length )

muls = np.array([cosine(row, next_user_stats) for row in users_stats])
best_user = np.argmax(muls)
print (best_user)

7
